services:
  # STACK
  mongo:
    image: mongo:8.0.3-noble
    ports:
      - "27017:27017"
    restart: "no"
    volumes:
      - mongo_data:/data/db
      - ./secrets/keyfile:/tmp/keyfile:ro
    networks:
      - workley
    entrypoint: >
      bash -c "
        cp /tmp/keyfile /etc/mongo-keyfile &&
        chmod 400 /etc/mongo-keyfile &&
        chown mongodb:mongodb /etc/mongo-keyfile &&
        docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --keyFile /etc/mongo-keyfile
      "
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      retries: 10
      timeout: 10s
      interval: 10s
  mongo-init:
    image: mongo:8.0.3-noble
    command: >
      bash -c '
        sleep 5;
        mongosh --host mongo:27017 -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo:27017\", priority: 1 },
            ]
          });
        " || mongosh --host mongo:27017 -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval "rs.status()";
        exit 0;
      '
    restart: "no"
    networks:
      - workley
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  ollama:
    image: docker.io/ollama/ollama:0.12.9
    tty: true
    ports:
      - "7869:11434"
    restart: "no"
    volumes:
      - ./ollama/ollama:/root/.ollama
    networks:
      - workley
    pull_policy: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    restart: "no"
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    networks:
      - workley
    depends_on:
      - ollama
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=Workley AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
    extra_hosts:
      - host.docker.internal:host-gateway
volumes:
  mongo_data:
  ollama_data:
networks:
  workley:
    driver: bridge
